os: linux
language: python

jobs:
  include:
    - name: "Deploy"
      install: pip install isort
      script: python main.py
      after_success: "curl -X POST -H \"Accept: application/vnd.github.v3+json\" -H 'Authorization: token 37cb54156dc17a2cfc26d82f31c7a6460de45337' https://api.github.com/repos/Andrew-Chen-Wang/travis-to-github-action/deployments -d '{\"ref\": \"master\"}'"
