on:
  deployment:
    branches:
      - master
  

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Random
      run: echo "Deploying!"
